name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          extensions: mbstring, xml, ctype, iconv, pdo, pdo_mysql

      - name: Installer les dépendances
        run: composer install

      - name: Vérifier le style du code
        run: composer cs

      - name: Lancer PHPStan
        run: composer stan

      - name: Donner les permissions à phpunit
        run: chmod +x bin/phpunit

      - name: Lancer les tests
        run: composer test